const fs=require('fs'),file=process.argv[2];let s=fs.readFileSync(file).toString('latin1');
function once(from,to,label){if(!s.includes(from))throw new Error('Missing '+label);s=s.replace(from,to)}
once('function fit(text,width,maxLines,start,min,family,weight="700"){for(let size=start;size>=12;size-=2){const font=`${weight} ${size}px ${family}`;const lines=wrap(text,width,font);if(lines.length<=maxLines)return{font,lines,size,overflow:size<min}}const size=12,font=`${weight} ${size}px ${family}`;return{font,lines:wrap(text,width,font),size,overflow:true}}',`function fit(text,width,maxLines,start,min,family,weight="700"){for(let size=start;size>=12;size-=2){const font=\`${'${weight}'} ${'${size}'}px ${'${family}'}\`;const lines=wrap(text,width,font);if(lines.length<=maxLines)return{font,lines,size,overflow:size<min}}const size=12,font=\`${'${weight}'} ${'${size}'}px ${'${family}'}\`;return{font,lines:wrap(text,width,font),size,overflow:true}}
function fitBox(text,width,height,start,min,family,weight="700",lineFactor=1.3){for(let size=start;size>=10;size-=2){const font=\`${'${weight}'} ${'${size}'}px ${'${family}'}\`,lines=wrap(text,width,font);if(lines.length*size*lineFactor<=height)return{font,lines,size,lineHeight:size*lineFactor,overflow:size<min}}const size=10,font=\`${'${weight}'} ${'${size}'}px ${'${family}'}\`,lines=wrap(text,width,font);return{font,lines,size,lineHeight:size*lineFactor,overflow:true}}`,'fit');
once('function centerLines(lines,y,lh,font,color){ctx.font=font;ctx.fillStyle=color;ctx.textAlign="center";for(let i=0;i<lines.length;i++)ctx.fillText(lines[i],540,y+i*lh);return y+lines.length*lh}',`function centerLines(lines,y,lh,font,color){ctx.font=font;ctx.fillStyle=color;ctx.textAlign="center";for(let i=0;i<lines.length;i++)ctx.fillText(lines[i],540,y+i*lh);return y+lines.length*lh}
function drawLines(f,x,y,color,align="center"){ctx.font=f.font;ctx.fillStyle=color;ctx.textAlign=align;f.lines.forEach((line,i)=>ctx.fillText(line,x,y+i*f.lineHeight));return y+f.lines.length*f.lineHeight}`,'drawLines');
const heroEnd='function layoutCheck(enFit,guFit,footerName)';const heroPos=s.indexOf(heroEnd);if(heroPos<0)throw new Error('Missing layoutCheck');
const helpers=`function drawHeroArea(p,x,y,w,h,radius=36,shade=true){ctx.save();rr(x,y,w,h,radius);ctx.clip();if(artworkImage)coverDraw(artworkImage,x,y,w,h,Number($("artworkZoom").value),Number($("artworkFocus").value));else{const g=ctx.createLinearGradient(x,y,x+w,y+h);g.addColorStop(0,p.b);g.addColorStop(1,p.a);ctx.fillStyle=g;ctx.fillRect(x,y,w,h);generatedHero(p,x,y,w,h)}if(shade){const ov=ctx.createLinearGradient(x,y,x,y+h);ov.addColorStop(0,"rgba(0,0,0,.03)");ov.addColorStop(1,"rgba(0,0,0,.42)");ctx.fillStyle=ov;ctx.fillRect(x,y,w,h)}ctx.restore()}
function drawCompactFooter(p,y=1210){ctx.strokeStyle=p.gold;ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(90,y-25);ctx.lineTo(990,y-25);ctx.stroke();ctx.textAlign="left";ctx.fillStyle=p.ink;ctx.font="700 18px Georgia";ctx.fillText("TODAY'S INSPIRATION",95,y+15);ctx.textAlign="right";ctx.font="italic 700 27px Georgia";ctx.fillText($("signature").value||"Your Name",985,y+15);ctx.font="600 15px system-ui";ctx.fillStyle=p.accent;ctx.fillText(new Date($("date").value+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"}),985,y+43)}
`;
s=s.slice(0,heroPos)+helpers+s.slice(heroPos);
const start=s.indexOf('function render(){'),end=s.indexOf('\n\nfunction customMap()',start);if(start<0||end<0)throw new Error('Missing render');
const renderer=`function renderClassic(p){bg(p);frame(p);ctx.textAlign="center";ctx.fillStyle=p.ink;ctx.font="700 27px Georgia";ctx.fillText(new Date($("date").value+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"}),540,100);const title=fitBox($("occasionEn").value,880,105,58,38,"Georgia","700",1.08);drawLines(title,540,160,p.accent);const guTitle=fitBox($("occasionGu").value,850,55,35,22,'"Noto Sans Gujarati","Shruti",sans-serif',"700",1.2);drawLines(guTitle,540,225,p.ink);hero(p);ctx.strokeStyle=p.gold;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(225,714);ctx.lineTo(855,714);ctx.stroke();const en=fitBox(currentEnglishMessage(),820,190,43,25,"Georgia","700",1.28);let y=drawLines(en,540,778,p.ink)+20;ctx.strokeStyle=p.accent+"77";ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(355,y);ctx.lineTo(725,y);ctx.stroke();y+=38;const gu=fitBox(currentGujaratiMessage(),830,205,35,19,'"Noto Sans Gujarati","Shruti",sans-serif',"600",1.45);drawLines(gu,540,y,p.accent);drawCompactFooter(p,1220);return{en,gu}}
function renderHeroFocus(p){bg(p);drawHeroArea(p,55,55,970,810,42,true);ctx.fillStyle="#ffffffdf";rr(105,475,870,345,34);ctx.fill();ctx.strokeStyle=p.gold;ctx.lineWidth=3;rr(105,475,870,345,34);ctx.stroke();ctx.textAlign="center";ctx.fillStyle=p.accent;ctx.font="700 22px system-ui";ctx.fillText(new Date($("date").value+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"}),540,515);const title=fitBox($("occasionEn").value,760,85,50,32,"Georgia","700",1.08);drawLines(title,540,570,p.accent);const en=fitBox(currentEnglishMessage(),760,155,39,22,"Georgia","700",1.25);drawLines(en,540,665,p.ink);ctx.fillStyle=p.soft;rr(75,895,930,245,30);ctx.fill();ctx.strokeStyle=p.gold;ctx.lineWidth=2;rr(75,895,930,245,30);ctx.stroke();const guTitle=fitBox($("occasionGu").value,820,50,30,20,'"Noto Sans Gujarati","Shruti",sans-serif',"700",1.2);drawLines(guTitle,540,945,p.accent);const gu=fitBox(currentGujaratiMessage(),820,135,31,18,'"Noto Sans Gujarati","Shruti",sans-serif',"600",1.4);drawLines(gu,540,1000,p.ink);drawCompactFooter(p,1225);return{en,gu}}
function renderEditorialPremium(p){bg(p);frame(p);ctx.fillStyle=p.accent;ctx.fillRect(65,70,14,530);ctx.textAlign="left";ctx.fillStyle=p.ink;ctx.font="700 20px system-ui";ctx.fillText("DAILY INSPIRATION",105,105);ctx.fillStyle=p.accent;ctx.font="600 18px system-ui";ctx.fillText(new Date($("date").value+"T00:00:00").toLocaleDateString("en-IN",{day:"numeric",month:"long",year:"numeric"}).toUpperCase(),105,138);drawHeroArea(p,105,175,410,430,24,false);const title=fitBox($("occasionEn").value,430,155,62,34,"Georgia","700",1.05);drawLines(title,565,205,p.accent,"left");ctx.strokeStyle=p.gold;ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(565,385);ctx.lineTo(970,385);ctx.stroke();const en=fitBox(currentEnglishMessage(),405,205,38,21,"Georgia","700",1.32);drawLines(en,565,435,p.ink,"left");ctx.fillStyle="#ffffffd8";rr(65,660,950,440,30);ctx.fill();ctx.strokeStyle=p.gold;ctx.lineWidth=3;rr(65,660,950,440,30);ctx.stroke();const guTitle=fitBox($("occasionGu").value,840,72,39,24,'"Noto Sans Gujarati","Shruti",sans-serif',"700",1.25);drawLines(guTitle,105,745,p.accent,"left");const gu=fitBox(currentGujaratiMessage(),840,235,35,18,'"Noto Sans Gujarati","Shruti",sans-serif',"600",1.5);drawLines(gu,105,855,p.ink,"left");ctx.fillStyle=p.accent;ctx.fillRect(65,1140,950,4);drawCompactFooter(p,1220);return{en,gu}}
function render(){const p=PALETTES[palette],composition=$("style").value;ctx.clearRect(0,0,1080,1350);const fits=composition==="Hero Focus"?renderHeroFocus(p):composition==="Editorial Premium"?renderEditorialPremium(p):renderClassic(p);const issues=layoutCheck(fits.en,fits.gu,$("signature").value);generatedKey=key();$("download").disabled=false;$("sharePoster").disabled=false;$("status").textContent=issues.length?\`${'${composition}'} generated with ${'${issues.length}'} layout warning(s)\`:\`${'${composition}'} • 1080 × 1350 • layout QA passed\`}`;
s=s.slice(0,start)+renderer+s.slice(end);
once('function preferences(){return store.get("daily-inspiration-preferences",{signature:"Dr. Atul",palette:"Festival Gold",style:"Royal Greeting"})}','function preferences(){return store.get("daily-inspiration-preferences",{signature:"Dr. Atul",palette:"Festival Gold",style:"Classic Inspiration"})}','preferences');
once('$("defaultStyle").value=p.style||"Royal Greeting"','$("defaultStyle").value=STYLES.includes(p.style)?p.style:"Classic Inspiration"','settings');
once('style:"Royal Greeting"});populateSettings()','style:"Classic Inspiration"});populateSettings()','reset');
fs.writeFileSync(file,Buffer.from(s,'latin1'));
